### ISSUE TITLE
Stringクラスの使用によるメモリリーク？

### ISSUE THREAD

**Issue by ainehanta** [PlantFactory/PFFIAPUploadAgent#1]
SerialCLIとの相性問題の可能性もある

**Comment by miettal** [comment]
あら、String使ってた。。
オリジナルに入ってないので、俺が血迷って入れた可能性が高いです。。
Stringはメモリ、プログラム領域馬鹿食いなので毛した方がいいですね。。

**Comment by miettal** [comment]
ちょっと考えなおしたのですが、やっぱりStringでいいかなと。
こっちのフォークは、できるだけArduino libraryのリッチな機能を使って、見通しのいいプログラムを作る方向が良いかなと感じています。
もともとのやつは、sramをできるだけ消費しないようにという設計だったので、こっちの設計はそうじゃない方向でやりたい。

**Comment by miettal** [comment]
メモリリーク?が発生する条件を教えて下さい

**Comment by ainehanta** [comment]
ちょっとまだ原因までわかってないので一旦クローズで．
Stringの実装見た感じだとあんまりメモリ再確保してなさそうでしたし．

**Comment by ainehanta** [comment]
リッチな方針で実装するのは賛成です．
